# Generated by Django 5.1.3 on 2024-12-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reservante', models.CharField(max_length=255)),
                ('dia_reserva', models.CharField(max_length=10)),
                ('asientos', models.IntegerField()),
                ('menu', models.CharField(max_length=255)),
            ],
        ),
    ]
