# Generated by Django 4.1.3 on 2025-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
